### ISSUE TITLE
Problem with Patchouli

### ISSUE THREAD

**Issue by Schaeferd-CZ** [EpicSquid/Roots#503]
I have problem with Patchouli minecraft crash.
Forge 1.12.2
**Mods:**
AIImprovements-1.12-0.0.1b3
OptiFine_1.12.2_HD_U_E3
TexFix+V-1.12-4.0
phosphor-1.12.2-0.2.6+build50-universal
Surge-1.12.2-2.0.77
foamfix-0.10.10-1.12.2

mysticalworld-1.12.2-1.8.4
Patchouli-1.0-20
mysticallib-1.12.2-1.7.0
Roots-1.12.2-3.0.28

**---- Minecraft Crash Report ----**

WARNING: coremods are present:
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/12/20 6:30 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Patchouli (patchouli)
Caused by: java.lang.NullPointerException
	at vazkii.patchouli.client.book.ClientBookRegistry.func_110549_a(ClientBookRegistry.java:83)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at vazkii.patchouli.client.book.ClientBookRegistry.init(ClientBookRegistry.java:62)
	at vazkii.patchouli.client.base.ClientProxy.preInit(ClientProxy.java:18)
	at vazkii.patchouli.common.base.Patchouli.preInit(Patchouli.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at magic.launcher.Launcher.main(SourceFile:214)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4654849832 bytes (4439 MB) / 5024776192 bytes (4792 MB) up to 5024776192 bytes (4792 MB)
	JVM Flags: 3 total; -Xms5000m -Xmx5000m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version        | Source                                      | Signature                                |
	|:----- |:----------------- |:-------------- |:------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2         | minecraft.jar                               | None                                     |
	| LCH   | mcp               | 9.42           | minecraft.jar                               | None                                     |
	| LCH   | FML               | 8.0.99.99      | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCH   | forge             | 14.23.5.2847   | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCH   | foamfixcore       | 7.7.4          | minecraft.jar                               | None                                     |
	| LCH   | aiimprovements    | 0.0.1.3        | AIImprovements-1.12-0.0.1b3.jar             | None                                     |
	| LCH   | foamfix           | 0.10.10-1.12.2 | foamfix-0.10.10-1.12.2.jar                  | None                                     |
	| LCH   | roots             | 1.12.2-3.0.28  | Roots-1.12.2-3.0.28.jar                     | None                                     |
	| LCH   | mysticalworld     | 1.12.2-1.8.4   | mysticalworld-1.12.2-1.8.4.jar              | None                                     |
	| LCE   | patchouli         | 1.0-20         | Patchouli-1.0-20.jar                        | None                                     |
	| LC    | surge             | 2.0.77         | Surge-1.12.2-2.0.77.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | texfix            | 4.0            | TexFix+V-1.12-4.0.jar                       | None                                     |
	| LC    | phosphor-lighting | 1.12.2-0.2.6   | phosphor-1.12.2-0.2.6+build50-universal.jar | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LC    | mysticallib       | 1.12.2-1.7.0   | mysticallib-1.12.2-1.7.0.jar                | None                                     |

	Loaded coremods (and transformers): 
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.5063' Renderer: 'Intel(R) HD Graphics 4400'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.5063
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by noobanidus** [comment]
Can you try deleting a file named similarly to "patchouli_data.json" from the root directory of your modpack?

**Comment by Schaeferd-CZ** [comment]
Sorry for being late :/ I removed mods that is useless except OptiFine. Here is shorter crash report. Now im going to do what you told me, but. . . i still cant find it :/ 
This might be pure **Roots** set.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 6/13/20 7:09 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Patchouli (patchouli)
Caused by: java.lang.NullPointerException
	at vazkii.patchouli.client.book.ClientBookRegistry.func_110549_a(ClientBookRegistry.java:83)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at vazkii.patchouli.client.book.ClientBookRegistry.init(ClientBookRegistry.java:62)
	at vazkii.patchouli.client.base.ClientProxy.preInit(ClientProxy.java:18)
	at vazkii.patchouli.common.base.Patchouli.preInit(Patchouli.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at magic.launcher.Launcher.main(SourceFile:214)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3869247768 bytes (3690 MB) / 5024776192 bytes (4792 MB) up to 5024776192 bytes (4792 MB)
	JVM Flags: 3 total; -Xms5000m -Xmx5000m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version       | Source                         | Signature |
	|:----- |:------------- |:------------- |:------------------------------ |:--------- |
	| LCH   | minecraft     | 1.12.2        | minecraft.jar                  | None      |
	| LCH   | mcp           | 9.42          | minecraft.jar                  | None      |
	| LCH   | FML           | 8.0.99.99     | forge-1.12.2-14.23.5.2847.jar  | None      |
	| LCH   | forge         | 14.23.5.2847  | forge-1.12.2-14.23.5.2847.jar  | None      |
	| LCH   | roots         | 1.12.2-3.0.28 | Roots-1.12.2-3.0.28.jar        | None      |
	| LCH   | mysticalworld | 1.12.2-1.8.4  | mysticalworld-1.12.2-1.8.4.jar | None      |
	| LCE   | patchouli     | 1.0-20        | Patchouli-1.0-20.jar           | None      |
	| LC    | mysticallib   | 1.12.2-1.7.0  | mysticallib-1.12.2-1.7.0.jar   | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.5063' Renderer: 'Intel(R) HD Graphics 4400'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.5063
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Schaeferd-CZ** [comment]
Hey I found this. May be useful

[19:16:23] [main/DEBUG] [FML]: Not found coremod data in mysticallib-1.12.2-1.7.0.jar
[19:16:23] [main/DEBUG] [FML]: Examining for coremod candidacy mysticalworld-1.12.2-1.8.4.jar
[19:16:23] [main/DEBUG] [FML]: Not found coremod data in mysticalworld-1.12.2-1.8.4.jar
[19:16:23] [main/DEBUG] [FML]: Examining for coremod candidacy OptiFine_1.12.2_HD_U_E3.jar
[19:16:23] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E3.jar
[19:16:23] [main/DEBUG] [FML]: Examining for coremod candidacy Patchouli-1.0-20.jar
[19:16:23] [main/DEBUG] [FML]: Not found coremod data in Patchouli-1.0-20.jar
[19:16:23] [main/DEBUG] [FML]: Examining for coremod candidacy Roots-1.12.2-3.0.28.jar
[19:16:23] [main/DEBUG] [FML]: Not found coremod data in Roots-1.12.2-3.0.28.jar

**Comment by Schaeferd-CZ** [comment]
And next one

19:16:40] [Client thread/DEBUG] [FML]: Mod Patchouli is missing a pack.mcmeta file, substituting a dummy one
[19:16:40] [Client thread/DEBUG] [FML]: Mod Roots is missing a pack.mcmeta file, substituting a dummy one

**Comment by noobanidus** [comment]
Could you please use gist.github.com to post your entire log? Those random sections are irrelevant debug statements; what appears to be happening is that the initial resource manager reload is causing the crash, as it takes place before Minecraft is actually available, but it attempts to access Minecraft.

I'm not entirely sure *what* is causing this to happen earlier than it should, though.

You mentioned trying it with moving out everything except Optifine -- can you please try it without Optifine? Especially as it has to do with resources/textures it's possible that there is some disparity there.

**Comment by noobanidus** [comment]
Actually, before all of that: what language is your system set to?
