### ISSUE TITLE
Server hangs when doing the Frost Lands ritual (in Nether?)

### ISSUE THREAD

**Issue by copygirl** [EpicSquid/Roots#505]
### General Information

**Describe the bug:**
Server hangs and subsequently crashes because tick took longer than 60 seconds whenever anyone logs in or comes close to the active Frost Lands ritual.

```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at net.minecraft.world.World.func_175624_G(World.java:3208)
	at net.minecraft.world.chunk.Chunk.func_186032_a(Chunk.java:472)
	at net.minecraft.world.chunk.Chunk.func_177435_g(Chunk.java:467)
	at net.minecraft.world.World.func_180495_p(World.java:912)
	at epicsquid.roots.entity.ritual.EntityRitualFrostLands.func_70071_h_(EntityRitualFrostLands.java:56)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce:**
Unsure, but the player who did this used the ritual multiple (3 to 4) times to create obsidian from lava in the Nether.

***

### Environment Versions

**Mystic Mods Versions:**
- MysticalLib: `1.7.0`
- Roots: `3.0.28`

**Other Versions:**
- Forge: `14.23.5.2854`
- Minecraft: `1.12.2`

***

### Logging Information

**Crash Report:**
[crash-2020-06-25_05.24.14-server.txt](https://gist.github.com/copygirl/db8720bc8c071935e800231a09984b2e)

**Latest Log:**
Doesn't appear to contain anything notable.

**Comment by noobanidus** [comment]
Hm. That's odd, I didn't consider the fact that snow isn't placeable in the Nether, ergo the break-out statement never reaches completion. I'll look at doing a 3.0.29 to fix it.

**Comment by copygirl** [comment]
I just realized that the :heart: reactions of my friend and I don't sufficiently express how impressed we are by your quick response, fix and release of an update to the mod. It's not something you can expect of most 1.12.2 mods. Thank you!
