### ISSUE TITLE
[alpha 8] Crash because of something

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#543]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/15/20 8:56 AM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:120)
	at epicsquid.roots.container.ContainerLibrary.func_184996_a(ContainerLibrary.java:275)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:120)
	at epicsquid.roots.container.ContainerLibrary.func_184996_a(ContainerLibrary.java:275)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: epicsquid.roots.client.gui.GuiLibrary

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Unever'/13, l='MpServer', x=671.49, y=4.00, z=-1695.32]]
	Chunk stats: MultiplayerChunkCache: 287, 287
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (629,4,-1702), Chunk: (at 5,0,10 in 39,-107; contains blocks 624,0,-1712 to 639,255,-1697), Region: (1,-4; contains chunks 32,-128 to 63,-97, blocks 512,0,-2048 to 1023,255,-1537)
	Level time: 12705 game time, 12705 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 15 total; [EntitySlime['Slime'/417, l='MpServer', x=623.49, y=4.14, z=-1668.00], EntitySlime['Slime'/387, l='MpServer', x=655.07, y=4.00, z=-1670.94], EntitySlime['Slime'/422, l='MpServer', x=711.23, y=4.42, z=-1730.69], EntitySlime['Slime'/391, l='MpServer', x=648.74, y=4.42, z=-1677.54], EntitySlime['Slime'/423, l='MpServer', x=695.68, y=4.00, z=-1721.20], EntitySlime['Slime'/204, l='MpServer', x=651.17, y=5.00, z=-1658.58], EntitySlime['Slime'/334, l='MpServer', x=694.33, y=5.25, z=-1705.12], EntitySlime['Slime'/401, l='MpServer', x=737.34, y=4.00, z=-1701.75], EntitySlime['Slime'/433, l='MpServer', x=605.41, y=4.00, z=-1616.70], EntitySlime['Slime'/405, l='MpServer', x=637.18, y=4.42, z=-1621.26], EntitySlime['Slime'/438, l='MpServer', x=621.70, y=5.02, z=-1674.36], EntityPlayerSP['Unever'/13, l='MpServer', x=671.49, y=4.00, z=-1695.32], EntitySlime['Slime'/439, l='MpServer', x=719.07, y=4.00, z=-1679.23], EntitySlime['Slime'/444, l='MpServer', x=711.99, y=4.00, z=-1719.03], EntitySlime['Slime'/447, l='MpServer', x=711.96, y=4.42, z=-1692.94]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1098307720 bytes (1047 MB) / 1543503872 bytes (1472 MB) up to 3724541952 bytes (3552 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx3548M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F4 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version              | Source                                | Signature                                |
	|:------ |:-------------------------- |:-------------------- |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2               | minecraft.jar                         | None                                     |
	| LCHIJA | mcp                        | 9.42                 | minecraft.jar                         | None                                     |
	| LCHIJA | FML                        | 8.0.99.99            | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                      | 14.23.5.2854         | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | jei                        | 4.16.1.302           | jei_1.12.2-4.16.1.302.jar             | None                                     |
	| LCHIJA | roots                      | 1.12.2-3.1.0-alpha8  | Roots-1.12.2-3.1.0-alpha8.jar         | None                                     |
	| LCHIJA | mysticalworld              | 1.12.2-1.9.3-alpha1  | mysticalworld-1.12.2-1.9.3-alpha1.jar | None                                     |
	| LCHIJA | patchouli                  | 1.0-21               | Patchouli-1.0-21-debug3.jar           | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4                  | tlskincape_1.12.2-1.4.jar             | None                                     |
	| LCHIJA | mysticallib                | 1.12.2-1.10.0-alpha1 | mysticallib-1.12.2-1.10.0-alpha1.jar  | None                                     |

	Loaded coremods (and transformers): 
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GT 540M/PCIe/SSE2'
	Patchouli open book context: n/a
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GT 540M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) CPU B950 @ 2.10GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GT 540M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by noobanidus** [comment]
Sorry, tlauncher is cracked and most likely won't work with the latest version of Roots.
