### ISSUE TITLE
Crash on making Block Elemental Soil in Lava 1.12.2

### ISSUE THREAD

**Issue by thediggyman** [EpicSquid/Roots#707]
### General Information

**Describe the bug:**
      **Throwing Block into lava crash game**

**To Reproduce:**

**Description: Ticking entity

java.lang.NullPointerException: Null string not allowed
	at java.util.Objects.requireNonNull(Unknown Source)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:138)
	at net.minecraft.entity.Entity.serializeNBT(Entity.java:3132)
	at com.natamus.configurabledespawntimer.events.ItemEvent.onItemJoinWorld(ItemEvent.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_889_ItemEvent_onItemJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1209)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at epicsquid.roots.event.handlers.ItemEventHandler.onEntityItemJoinWorld(ItemEventHandler.java:113)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_190_ItemEventHandler_onEntityItemJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1209)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at epicsquid.roots.item.itemblock.ItemBlockElementalSoil.onEntityItemUpdate(ItemBlockElementalSoil.java:49)
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:87)
	at realdrops.entities.EntityItemLoot.func_70071_h_(EntityItemLoot.java:116)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)**

**Expected behavior:**

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 
- Ecc...

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:
- Minecraft:
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Objects.requireNonNull(Unknown Source)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:138)
	at net.minecraft.entity.Entity.serializeNBT(Entity.java:3132)
	at com.natamus.configurabledespawntimer.events.ItemEvent.onItemJoinWorld(ItemEvent.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_889_ItemEvent_onItemJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1209)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at epicsquid.roots.event.handlers.ItemEventHandler.onEntityItemJoinWorld(ItemEventHandler.java:113)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_190_ItemEventHandler_onEntityItemJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1209)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at epicsquid.roots.item.itemblock.ItemBlockElementalSoil.onEntityItemUpdate(ItemBlockElementalSoil.java:49)
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:87)
	at realdrops.entities.EntityItemLoot.func_70071_h_(EntityItemLoot.java:116)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: realdrops:item_loot (realdrops.entities.EntityItemLoot)
	Entity ID: 411
	Entity Name: item.tile.elemental_soil
	Entity's Exact location: 264.66, 64.89, 304.70
	Entity's Block location: World: (264,64,304), Chunk: (at 8,4,0 in 16,19; contains blocks 256,0,304 to 271,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.05, 0.20, -0.03
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Druids Life
	All players: 1 total; [EntityPlayerMP['THEDIGGYMAN'/310, l='Druids Life', x=264.72, y=65.00, z=305.78]]
	Chunk stats: ServerChunkCache: 289 Drop: 0
	Level seed: 0
	Level generator: ID 06 - OTG, ver 0. Features enabled: true
	Level generator options: OpenTerrainGenerator
	Level spawn location: World: (252,63,367), Chunk: (at 12,3,15 in 15,22; contains blocks 240,0,352 to 255,255,367), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1042645 game time, 1042645 day time
	Level dimension: 21
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 136641 (now: false), thunder time: 34415 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6259157976 bytes (5969 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 5 total; -Xms8192m -Xmx8192m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
From the crash report this would appear to be a conflict with `com.natamus.configurabledespawntimer`.

Given that it functions perfectly without this mod, I'd suggest reporting it to them.
