### ISSUE TITLE
Game crashing (going back to main menu) when right clicking with a firestarter on a Pyre

### ISSUE THREAD

**Issue by InterPlay02** [EpicSquid/Roots#808]
### General Information

**Describe the bug:**
That's exactly it. The game crashes and goes back to main menu when I right click with a firestarter on a Pyre.

**Expected behavior:**
Should start the fire, or do nothing?

### Environment Versions
3.1.8 of the mod and Minecraft 1.12.2

**Mystic Mods Versions**
Is that even a thing?

**Other Versions:**
- Other mods you think could cause issues:
I don't think that's the case, because the game was running smoothly until I tried to right click the Pyre.

- Forge: 14.23.5.2860
- Minecraft: 1.12.2
- Modpack: Magical Exploration (on Curse Forge)

***

### Logging Information
https://github.com/InterPlay02/Random-Codes/blob/principal/Roots%20crash.log

**Crash Report (if available):**

_[15:13:21] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.world.World.updateEntities(World.java:1776) ~[amu.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847) ~[bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`
**Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.entity.Entity.field_70146_Z from class epicsquid.roots.item.ItemFireStarter
	at epicsquid.roots.item.ItemFireStarter.onUsingTick(ItemFireStarter.java:110) ~[ItemFireStarter.class:?]**
	at net.minecraft.entity.EntityLivingBase.updateActiveHand(EntityLivingBase.java:2678) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2097) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:181) ~[bud.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) ~[amu.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1958) ~[amu.class:?]
	at net.minecraft.world.World.redirect$zdm000$updateEntity(World.java:4123) ~[amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1762) ~[amu.class:?]
	... 10 more
[15:13:21] [Client thread/FATAL]: Minecraft ran into a problem! Report saved to: D:\XboxGames\Instances\Magical Exploration\crash-reports\crash-2024-01-05_15.13.21-client.txt
---- Minecraft Crash Report ----
// This doesn't make any sense!_

**Comment by InterPlay02** [comment]
I just noticed that actually it is crashing back to main menu when right clicking on anything.
(while holding the firestarter)

**Comment by noobanidus** [comment]
I'm very confused why this is happening... so, what's going on here is that the Firestarter item is accessing a value that is being made public by an access transformer but which is, by default, not publicly accessible.

For some reason the version you have doesn't have this access transformer applied properly, for whatever reason -- a bug in how ForgeGradle and other systems function in 1.12.2.

This means that the firestarter won't work for you; you could try bypassing using it and just using a flint and steel instead.

Alternately, you could try downgrading to 3.1.6 instead -- I believe that should work properly, but there might be other issues.

Unfortunately I don't even have a current build environment set up for Roots, your best bet would be to try contacting ByThePowerOfScience through the Mystic Modding Discord directly, but I'm unsure if they have time to commit to the project currently.

**Comment by ByThePowerOfScience** [comment]
I'm not sure what the deal is with the access transformer either.  I'll take a look.
